name: Push to registry

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: tul1/lawnmower:${{ steps.get_tag_name.outputs.VERSION }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

